server:
    port: 8080
spring:
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        url: jdbc:mysql://127.0.0.1:3306/yimei?serverTimezone=UTC
        username: root
        password: root
mybatis:
    type-aliases-package: com.example.yimeimaven.entity
    mapper-locations: classpath:mapper/*xml